# Banco de dados
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=paroquia
quarkus.datasource.password=paroquia123
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/paroquia

# Hibernate
quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.log.sql=true

# Desabilitar OIDC por enquanto (Keycloak vem depois)
quarkus.oidc.enabled=false
quarkus.oidc.tenant-enabled=false

# Swagger UI sempre visível
quarkus.swagger-ui.always-include=true